from __future__ import annotations

import asyncio
import os
import tempfile
from typing import Any

from interpiped.agents.base import BaseAgent
from interpiped.events import schemas
from interpiped.services.git_service import GitService, GitServiceError


class WorkerAgent(BaseAgent):
    """Example worker agent that listens for TaskCreated and emits TaskCompleted."""

    def __init__(self, name: str, bus):
        super().__init__(name, bus)
        self._started = False

    async def start(self) -> None:
        if self._started:
            return
        await self.bus.subscribe("TaskCreated", self.handle_event)
        self._started = True

    async def stop(self) -> None:
        # InMemoryEventBus does not currently support unsubscribe; noop for now
        self._started = False

    async def handle_event(self, event: Any) -> None:
        # Handle TaskCreated: perform repo workflow and emit TaskCompleted
        if getattr(event, "event_type", None) != "TaskCreated":
            return

        task_id = getattr(event, "task_id", "unknown-task")
        repository = getattr(event, "repository", None)
        branch_name = getattr(event, "branch_name", f"task/{task_id}")
        title = getattr(event, "title", "")
        description = getattr(event, "description", "")

        # perform git operations in a temporary directory
        tmpdir = tempfile.mkdtemp(prefix="interpiped-")
        try:
            # clone repository
            gs = GitService.clone_repository(str(repository), tmpdir)

            # create and checkout branch
            gs.create_branch(branch_name)

            # create tasks directory and placeholder file
            tasks_dir = os.path.join(gs.repo_path, "tasks")
            os.makedirs(tasks_dir, exist_ok=True)
            filename = f"{task_id}.md"
            filepath = os.path.join(tasks_dir, filename)
            content = f"# Task\nGenerated by InterPipeD\n\nTask ID: {task_id}\n\nDescription:\n{description}\n"
            with open(filepath, "w", encoding="utf-8") as fh:
                fh.write(content)

            # commit changes
            commit_message = f"feat(task): {task_id}"
            gs.commit_all(commit_message)

            # collect result
            sha = gs.get_current_commit_sha()
            rel_path = os.path.relpath(filepath, gs.repo_path)
            files_modified = [rel_path]

            completed = schemas.TaskCompleted(
                task_id=task_id,
                commit_sha=sha,
                files_modified=files_modified,
                source=self.name,
            )

            await self.bus.publish(completed)
        except GitServiceError:
            # log and re-raise or publish failed event in future; for now just log
            # avoid crashing the event loop
            import logging

            logging.getLogger(__name__).exception("git operation failed for task %s", task_id)
        finally:
            # do not remove tmpdir to allow inspection in tests if needed
            await asyncio.sleep(0)
