from __future__ import annotations

import asyncio
import os
import tempfile
from typing import Any

from interpiped.agents.base import BaseAgent
from interpiped.events import schemas
from interpiped.services.git_service import GitService, GitServiceError


class WorkerAgent(BaseAgent):
    """Example worker agent that listens for TaskCreated and emits TaskCompleted."""

    def __init__(self, name: str, bus):
        super().__init__(name, bus)
        self._started = False

    async def start(self) -> None:
        if self._started:
            return
        await self.bus.subscribe("TaskCreated", self.handle_event)
        await self.bus.subscribe("RetryRequested", self.handle_retry)
        self._started = True

    async def stop(self) -> None:
        # InMemoryEventBus does not currently support unsubscribe; noop for now
        self._started = False

    async def handle_event(self, event: Any) -> None:
        # Handle TaskCreated: perform repo workflow and emit TaskCompleted
        if getattr(event, "event_type", None) != "TaskCreated":
            return

        task_id = getattr(event, "task_id", "unknown-task")
        repository = getattr(event, "repository", None)
        branch_name = getattr(event, "branch_name", f"task/{task_id}")
        title = getattr(event, "title", "")
        description = getattr(event, "description", "")

        await self._process_task(task_id, repository, branch_name, title, description)

    async def handle_retry(self, event: Any) -> None:
        if getattr(event, "event_type", None) != "RetryRequested":
            return

        task_id = getattr(event, "task_id")
        repository = getattr(event, "repository", None)
        branch_name = getattr(event, "branch_name", f"task/{task_id}")
        title = getattr(event, "title", "")
        description = getattr(event, "description", "")

        await self._process_task(task_id, repository, branch_name, title, description)

    async def _process_task(self, task_id: str, repository: str | None, branch_name: str, title: str, description: str) -> None:
        tmpdir = tempfile.mkdtemp(prefix="interpiped-")
        try:
            gs = GitService.clone_repository(str(repository), tmpdir)
            gs.create_branch(branch_name)

            tasks_dir = os.path.join(gs.repo_path, "tasks")
            os.makedirs(tasks_dir, exist_ok=True)
            filename = f"{task_id}.md"
            filepath = os.path.join(tasks_dir, filename)
            content = f"# Task\nGenerated by InterPipeD\n\nTask ID: {task_id}\n\nDescription:\n{description}\n"
            with open(filepath, "w", encoding="utf-8") as fh:
                fh.write(content)

            commit_message = f"feat(task): {task_id}"
            gs.commit_all(commit_message)

            sha = gs.get_current_commit_sha()
            rel_path = os.path.relpath(filepath, gs.repo_path)
            files_modified = [rel_path]

            completed = schemas.TaskCompleted(
                task_id=task_id,
                commit_sha=sha,
                files_modified=files_modified,
                source=self.name,
            )

            await self.bus.publish(completed)
        except Exception as e:
            import logging

            logging.getLogger(__name__).exception("git operation failed for task %s", task_id)
            failed = schemas.TaskFailed(
                task_id=task_id,
                reason=str(e),
                error_type=type(e).__name__,
                source=self.name,
            )
            try:
                await self.bus.publish(failed)
            except Exception:
                logging.getLogger(__name__).exception("failed to publish TaskFailed for %s", task_id)
        finally:
            await asyncio.sleep(0)
